routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::resource('position',PositionController::class);
Route::resource('employee',EmployeeController::class);

resources/views/employee.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
        <button type="button" class="btn btn-primary add-btn" data-toggle="modal" data-target="#addemployeeModal">
          Add Position
        </button>
    </div>
    @if (count($errors)>0)
        <div class="alert alert-danger">
          <ul class="list-unstyled">
            @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
          </ul>
        </div>
    @endif
    <div class="card-body">
        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTable">
              <thead class="thead-light">
                <tr>
                  <th>No.</th>
                  <th>Nama Jabatan</th>
                  <th>Departemen</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @php
                    $i = 1;
                @endphp
                @foreach ($employee as $item)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$item->nama}}</td>
                  <td>{{$item->position->nama_jabatan}}</td>
                  <td>
                    @if($item->status == 1)
                    <button class="btn btn-outline-success btn-sm" style="width: 100%" disabled>Active</button>
                  @else
                  <button class="btn btn-outline-danger btn-sm" style="width: 100%" disabled>Nonactive</button>
                  @endif
                
                  </td>
                  <td>
                    <a href="{{ route('employee.show', $item->id) }}" class="btn btn-light" ><i class="fa fa-eye"></i></a>
                    <a href="" class="btn btn-warning" data-toggle="modal" data-target="#updateModal{{$item->id}}"><i class="fa fa-edit"></i></a>
                    {{-- <a href="{{ route('position.destroy', $item->id) }}" class="btn btn-warning"><i class="fa fa-pencil-square"></i></a> --}}
                   
                    <form class="d-inline" action="{{ route('employee.destroy', $item->id) }}" method="POST">
                      @csrf
                      @method('DELETE')
                      <button type="submit" class="btn btn-danger" ><i class="fa fa-trash"></i></button>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
    </div>
</div>






@include('sweetalert::alert')
@include('employeeAdd')
@include('employeeEdit')

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

@endpush

resources/views/employeeAdd.blade.php
<!-- Modal -->
<div class="modal fade" id="addemployeeModal" tabindex="-1" aria-labelledby="addemployeeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addemployeeModalLabel">Add Position</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
         <form action="{{route('employee.store')}}" method="POST" enctype="multipart/form-data">
          @csrf
            <div class="row">
              <div class="col-lg-12 mb-2">
                  <label for="nama">Jabatan</label>
                  <select class="default-select wide form-control" name="position_id">
                      <option disabled selected>--pilih jabatan--</option>
                  @foreach($position as $item)
                      <option value="{{$item->id}}">{{$item->nama_jabatan}}</option>
                  @endforeach
              </select>
                </div>
              <div class="col-lg-12 mb-2">
                <label for="nama">Nama</label>
                <input type="text" name="nama" id="nama" class="form-control" required>
                @error('nama')
                  {{$message}}
                @enderror
              </div>
              
              <div class="col-lg-12 mb-2">
                <label for="NIP">NIP</label>
                <input type="text" name="NIP" id="NIP" class="form-control">
                @error('NIP') 
                  <span class="text-danger">{{$message}}</span>
                @enderror
              </div>
              <div class="col-lg-12 mb-2">
                  <label for="tanggal_lahir">Tanggal Lahir</label>
                  <input type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control" required>
                </div>
                <div class="col-lg-12 mb-2">
                  <label for="alamat">Alamat</label>
                  <input type="text" name="alamat" id="alamat" class="form-control" required>
                </div>
                <div class="col-lg-12 mb-2">
                  <label for="no_telepon">Nomer Telepon</label>
                  <input type="text" name="no_telepon" id="no_telepon" class="form-control" required>
                </div>
                <div class="col-lg-12 mb-2">
                  <label for="agama">Agama</label> <br>
                  <input type="radio" value="Islam" id="islam" name="agama">
                  <label for="islam">Islam</label>&nbsp
                  <input type="radio" value="Kristen" id="kristen" name="agama">
                  <label for="kristen">Kristen</label>&nbsp
                  <input type="radio" value="Hindu" id="hindu" name="agama">
                  <label for="hindu">Hindu</label>&nbsp
                  <input type="radio" value="Buddha" id="buddha" name="agama">
                  <label for="buddha">Buddha</label>&nbsp
                  <input type="radio" value="Katolik" id="katolik" name="agama">
                  <label for="katolik">Katolik</label>&nbsp
                  <input type="radio" value="Konghuchu" id="Konghuchu" name="agama">
                  <label for="Konghuchu">Kong hu Chu</label>
                </div>
                <div class="col-lg-12 mb-2">
                  <label for="status">status</label>
                  <select class="default-select wide form-control" name="status">
                      <option disabled selected>--pilih status--</option>
                      <option value="1">Active</option>
                      <option value="0">Nonactive</option>
                  </select>
                </div>
                <div class="col-lg-12 mb-2">
                  <label for="file_ktp">Foto KTP</label>
                  <input type="file" name="file_ktp" id="file_ktp" class="form-control" required>
                </div>
            </div>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary btn-save">Add Employee</button>
        </div>
      </form>
      </div>
    </div>
  </div>

resources/views/employeeDetail.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
        <a href="{{ route('employee.index') }}" class="btn btn-success">Back</a>
    </div>
    <div class="card-body">
        <div class="table-responsive p-3">
            <table class="table table-bordered align-items-center table-flush" id="dataTable">
                @php
                    $i = 1;
                @endphp
                <tr>
                  <th width="25%">No </th>
                  <td>:&nbsp{{$i++}}</td>
                </tr>
                <tr>
                    <th>Nama </th>
                    <td>:&nbsp{{$employee->nama}}</td>
                </tr>
                <tr>
                    <th>NIP </th>
                    <td>:&nbsp{{$employee->NIP}}</td>
                </tr> 
                <tr>
                    <th>Jabatan </th>
                    <td>:&nbsp{{$employee->position->nama_jabatan}}</td>
                </tr>
                <tr>
                    <th>Departemen </th>
                    <td>:&nbsp{{$employee->position->departemen}}</td>
                </tr>
                <tr>
                    <th>Tanggal Lahir </th>
                    <td>:&nbsp{{$employee->tanggal_lahir}}</td>
                </tr> 
                <tr>
                    <th>Alamat </th>
                    <td>:&nbsp{{$employee->alamat}}</td>
                </tr> 
                <tr>
                    <th>No Telepon </th>
                    <td>:&nbsp{{$employee->no_telepon}}</td>
                </tr> 
                <tr>
                    <th>Agama</th>
                    <td>:&nbsp{{$employee->agama}}</td>
                </tr> 
                <tr>
                    <th>Status</th>
                    <td>
                        @if($employee->status == 1)
                        <button class="btn btn-outline-success btn-sm" style="width: 25%" disabled>Active</button>
                      @else
                      <button class="btn btn-outline-danger btn-sm" style="width: 25%" disabled>Nonactive</button>
                      @endif
                    </td>
                </tr> 
                <tr>
                    <th>Foto KTP</th>
                    <td><img src="{{asset('upload/'.$employee->file_ktp) }}" width="120px"></td>
                </tr>
            
            </table>
          </div>
    </div>
</div>



@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

@endpush

resources/views/employeeEdit.blade.php
@foreach ($employee as $data)
<div class="modal fade" id="updateModal{{ $data->id }}" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Edit Position</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form action="{{ route('employee.update', $data->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-lg-12 form-group mb-2">
                <label for="nama">Jabatan</label>
                <select class="default-select wide form-control" name="position_id">
                    <option value="{{$data->position_id}}">{{$data->position->nama_jabatan}}</option>
                @foreach($position as $item)
                    <option value="{{$item->id}}">{{$item->nama_jabatan}}</option>
                @endforeach
            </select>
              </div>
            <div class="form-group col-lg-12 mb-2">
              <label for="nama">Nama</label>
              <input type="text" name="nama" id="nama" value="{{$data->nama}}" class="form-control" required>
              
            </div>
            
            <div class="form-group col-lg-12 mb-2">
              <label for="NIP">NIP</label>
              <input type="text" name="NIP" id="NIP" value="{{$data->NIP}}" class="form-control @error('NIP') is-invalid @enderror">
              @error('NIP') 
                <span class="text-danger">{{$message}}</span>
              @enderror
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="tanggal_lahir">Tanggal Lahir</label>
                <input type="date" name="tanggal_lahir" value="{{$data->tanggal_lahir}}" id="tanggal_lahir" class="form-control" required>
              </div>
              <div class="form-group col-lg-12 mb-2">
                <label for="alamat">Alamat</label>
                <input type="text" name="alamat" id="alamat" value="{{$data->alamat}}" class="form-control" required>
              </div>
              <div class="form-group col-lg-12 mb-2">
                <label for="no_telepon">Nomer Telepon</label>
                <input type="text" name="no_telepon" id="no_telepon" value="{{$data->no_telepon}}" class="form-control" required>
              </div>
              <div class="form-group col-lg-12 mb-2">
                <label for="agama">Agama</label> <br>
                <input type="radio" value="Islam" id="islam" name="agama" {{$data->agama == 'Islam' ? 'checked' : ''}}>
                <label for="islam">Islam</label>&nbsp
                <input type="radio" value="Kristen" id="kristen" name="agama" {{$data->agama == 'Kristen' ? 'checked' : ''}}>
                <label for="kristen">Kristen</label>&nbsp
                <input type="radio" value="Hindu" id="hindu" name="agama" {{$data->agama == 'Hindu' ? 'checked' : ''}}>
                <label for="hindu">Hindu</label>&nbsp
                <input type="radio" value="Buddha" id="buddha" name="agama" {{$data->agama == 'Buddha' ? 'checked' : ''}}>
                <label for="buddha">Buddha</label>&nbsp
                <input type="radio" value="Katolik" id="katolik" name="agama" {{$data->agama == 'Katolik' ? 'checked' : ''}}>
                <label for="katolik">Katolik</label>&nbsp
                <input type="radio" value="Konghuchu" id="Konghuchu" name="agama" {{$data->agama == 'Konghuchu' ? 'checked' : ''}}>
                <label for="Konghuchu">Kong hu Chu</label>
              </div>
              <div class="form-group col-lg-12 mb-2">
                <label for="status">status</label>
                <select class="default-select wide form-control" name="status">
                    @if ($data->status == 1)
                    <option value="1" selected>Active</option>
                    <option value="0">Nonactive</option>
                    @else
                    <option value="1">Active</option>
                    <option value="0" selected>Nonactive</option>
                    @endif
                    
                    
                </select>
              </div>
              <div class="form-group col-lg-12 mb-2">
                <label for="file_ktp">Foto KTP</label>
                <input type="file" name="file_ktp" id="file_ktp" class="form-control">
                <img src="{{ asset('upload/'.$data->file_ktp) }}" width="120px">
              </div>
          </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary btn-save">Add position</button>
      </div>
    </form>
    </div>
  </div>
</div>
@endforeach

resources/views/position.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
        <button type="button" class="btn btn-primary add-btn" data-toggle="modal" data-target="#addpositionModal">
          Add Position
        </button>
    </div>
    <div class="card-body">
        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTable">
              <thead class="thead-light">
                <tr>
                  <th>No.</th>
                  <th>Nama Jabatan</th>
                  <th>Departemen</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @php
                    $i = 1;
                @endphp
                @foreach ($positions as $item)
                <tr>
                  <td>{{$i++}}</td>
                  <td>{{$item->nama_jabatan}}</td>
                  <td>{{$item->departemen}}</td>
                  <td>
                    <a href="" class="btn btn-warning" data-toggle="modal" data-target="#updateModal{{$item->id}}"><i class="fa fa-edit"></i></a>
                    {{-- <a href="{{ route('position.destroy', $item->id) }}" class="btn btn-warning"><i class="fa fa-pencil-square"></i></a> --}}
                   
                    <form class="d-inline" action="{{ route('position.destroy', $item->id) }}" method="POST">
                      @csrf
                      @method('DELETE')
                      <button type="submit" class="btn btn-danger" ><i class="fa fa-trash"></i></button>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="addpositionModal" tabindex="-1" aria-labelledby="addpositionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addpositionModalLabel">Add Position</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form action="{{route('position.store')}}" method="POST">
        @csrf
          <div class="row">
            <div class="col-lg-12 mb-2">
              <label for="nama">Nama Jabatan</label>
              <input type="text" name="nama_jabatan" id="nama_jabatan" class="form-control @error('nama_jabatan') is-invalid @enderror" required>
              @error('nama_jabatan')
                  <span class="text-danger">{{$message}}</span>
              @enderror
            </div>
            <div class="col-lg-12 mb-2">
              <label for="nama">Departemen</label>
              <input type="text" name="departemen" id="departemen" class="form-control" required>
            </div>
          </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary btn-save">Add position</button>
      </div>
    </form>
    </div>
  </div>
</div>

@foreach ($positions as $data)
<div class="modal fade" id="updateModal{{ $data->id }}" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Edit Position</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form action="{{ route('position.update', $data->id) }}" method="POST">
        @csrf
        @method('PUT')
          <div class="row">
            <div class="col-lg-12 mb-2">
              <label for="nama">Nama Jabatan</label>
              <input type="text" name="nama_jabatan" id="nama_jabatan" value="{{$data->nama_jabatan}}" class="form-control" required>
            </div>
            <div class="col-lg-12 mb-2">
              <label for="nama">Departemen</label>
              <input type="text" name="departemen" id="departemen" value="{{$data->departemen}}" class="form-control" required>
            </div>
          </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary btn-save">Add position</button>
      </div>
    </form>
    </div>
  </div>
</div>
@endforeach

@include('sweetalert::alert')
@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

{{-- <script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'nama_jabatan' },
            { data: 'departemen' }
        ]
    });

    $.ajaxSetup({
      headers:{
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    })

    $('body').on('click', '.add-btn', function(e){
        e.preventDefault();
        $('#addpositionModal').modal('show');

        $('.btn-save').click(function(){
          

          $.ajax({
            url: 'position',
            type: 'POST',
            data:{
              nama_jabatan: $('#nama_jabatan').val(),
              departemen: $('#departemen').val()
            },
            dataType: 'JSON',
            success: function(response){
             
                // alert('Berhasil');
                $('#nama_jabatan').val('');
                $('#departemen').val('');
                $('#addpositionModal').modal('hide');
                $('#dataTable').DataTable().ajax.reload()
            }
            
          });

          
        });
    });

</script> --}}
@endpush